DROP TABLE IF EXISTS prr_users_has_groups CASCADE; 
DROP TABLE IF EXISTS prr_users CASCADE; 
DROP TABLE IF EXISTS prr_groups CASCADE; 
DROP TABLE IF EXISTS prr_product CASCADE; 
DROP TABLE IF EXISTS prr_team CASCADE; 
DROP TABLE IF EXISTS prr_users_has_teams CASCADE; 
DROP TABLE IF EXISTS prr_app CASCADE;