DROP TABLE IF EXISTS prr_users_has_groups CASCADE; 
DROP TABLE IF EXISTS prr_users CASCADE; 
DROP TABLE IF EXISTS prr_groups CASCADE; 
DROP TABLE IF EXISTS prr_products CASCADE; 
DROP TABLE IF EXISTS prr_teams CASCADE; 
DROP TABLE IF EXISTS prr_users_has_teams CASCADE; 
DROP TABLE IF EXISTS prr_apps CASCADE;